repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 21.9b0  # Use the latest version
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3  # Use the latest version
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2  # Use the latest version
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812  # Use the latest version
    hooks:
    -   id: mypy
        args: ['--ignore-missing-imports']

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the latest version
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-use-type-annotations
